### ISSUE TITLE
Implement Preferences Page

### ISSUE THREAD

**Issue by mustafadurmusNl** [HackYourFuture/Assignments#110]
**Acceptance Criteria:**

- [ ] On first registration, the user is directed to the Preferences Page.

- [ ] On the Preferences Page, the user is asked to select their favorite book genres (e.g., "Fiction," "Science," "Romance").

- [ ] Once the user selects their genres, this information is saved.

- [ ] After saving, the app will display books from these genres every time the user logs in.

- [ ] The user can update or change their genre preferences later if needed.

**Comment by remarcmij** [comment]
This issue needs to go elsewhere.
